name: CI

on:
  push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Use Node.js 10.13.0
      uses: actions/setup-node@v1
      with:
        node-version: '10.13.0'
    - name: Install all development dependencies
      run: npm ci
    - name: 'Run tests'
      run: npm test
